development:
  adapter: postgresql
  encoding: unicode
  database: soundboardz_development
  pool: 5
  username: soundboardz
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: soundboardz_test
  pool: 5
  username: soundboardz
  password: password
